project:
  type: website
  output-dir: docs
  resources:
    - Syllabus52725.pdf

website:
  page-navigation: true
  title: "StatQuest"
  description: "Homepage for StatQuest Workshop"
  favicon: /images/icon.png

  repo-url: https://github.com/meganhokama/workshop
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#EF4056" # AZ Red
    logo: "images/icon.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/meganhokama
        text: "GitHub organization"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Workshop information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Materials"
        contents:
          - href: rstudio.qmd
            text: Installing R/RStudio
          - href: twine.qmd
            text: Twine Game
          - href: lecture.qmd
            text: Lecture and R-scripts
            
  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Meg Hokama"
    background: "#AB0520" # AZ Red

format:
  html:
    theme:
      light: [cosmo, style/info526.scss]
      dark: [cosmo, style/info526.scss, style/dark.scss]
    linkcolor: "#EF4056" # Azurite
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Montserrat"

execute:
  freeze: auto

editor: visual
