---
title: "StatQuest"
subtitle: "Dr. Kat Cheng & Meg Hokama"
execute:
  freeze: false
editor_options: 
  chunk_output_type: console
---

This page contains an outline of the topics and content for the workshop. If you would like to sign up for the [**survey or workshop,**]{.underline} please go to this link \[[here](https://uarizona.co1.qualtrics.com/jfe/form/SV_25FhRK3lFq3HQX4)\].

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1fEYzqlRPp1BCag_YzWvUmxWNyMzNaPaM6OtNIkYBFdo/edit?usp=sharing")
```

```{r}
#| echo: false

d |>
  mutate(
    date = as.Date(date)
  ) |>
  gt() |>
  fmt_date(date, date_style = 31) |>
  sub_missing(columns = c(day, what, topic), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(day)
    ) |>
  cols_align(
    align = "right", 
    columns = c(date)
    ) |>
  cols_align(
    align = "left", 
    columns = c(what, topic, rworkshop, game)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, what, rworkshop, game)
    )
  ) |>
  fmt_markdown(
    columns = c(topic)
  ) |>
  cols_width(
    day ~ px(30),
    date ~ px(200), 
    topic ~ px(400),
    topic ~ px(300),
  ) |>
  cols_label(
    what = "Lecture",
    day = "Day",
    date = "Date", 
    topic = "Topic",
    rworkshop = "R-Workshop",
    game = "Twine Game"
  ) |>
  tab_options(
    table.font.names = "Raleway",
  )
```
